services:
    postgres:
        container_name: music-service
        image: postgres:17
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        ports:
            - 5437:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - music-service

volumes:
    postgres_data:

networks:
    music-service:
